// @ts-nocheck
import * as React from "react"

export const Index: Record<string, any> = {
  default: {
    accordion: {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/accordion.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/accordion")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/ui/alert-dialog.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/alert-dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    button: {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/button.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/button")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    checkbox: {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/checkbox.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/checkbox")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    collapsible: {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/collapsible.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/collapsible")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    dialog: {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/dialog.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    menu: {
      name: "menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/menu.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "preview-card": {
      name: "preview-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/preview-card.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/preview-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    input: {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/input.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    label: {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/label.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    popover: {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/popover.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/popover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    progress: {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/progress.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/progress.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    radio: {
      name: "radio",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/radio.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/radio.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/scroll-area.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/scroll-area.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    select: {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/select.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/select.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    separator: {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/separator.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/separator.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    slider: {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/slider.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/slider.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    switch: {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/switch.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/switch.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    tabs: {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/tabs.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/tabs")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    // textarea: {
    //   name: "textarea",
    //   description: "",
    //   type: "registry:ui",
    //   registryDependencies: undefined,
    //   files: [
    //     {
    //       path: "src/components/ui/textarea.tsx",
    //       type: "registry:ui",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(() => import("@/components/ui/textarea.tsx")),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    toggle: {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/toggle.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    tooltip: {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "src/components/ui/tooltip.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/ui/tooltip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "accordion-demo": {
      name: "accordion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [
        {
          path: "src/components/examples/accordion-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/accordion-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "alert-dialog-demo": {
      name: "alert-dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert-dialog", "button"],
      files: [
        {
          path: "src/components/examples/alert-dialog-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/alert-dialog-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/button-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-secondary.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/button-secondary"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-destructive.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/button-destructive"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-outline": {
      name: "button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-outline.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/button-outline"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-ghost.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/button-ghost")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-link.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/button-link")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-with-icon": {
      name: "button-with-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-with-icon.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/button-with-icon"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-loading.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/button-loading"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/examples/button-icon.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/button-icon")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "checkbox-demo": {
      name: "checkbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [
        {
          path: "src/components/examples/checkbox-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/checkbox-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "checkbox-disabled": {
      name: "checkbox-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [
        {
          path: "src/components/examples/checkbox-disabled.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/checkbox-disabled"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "checkbox-group": {
      name: "checkbox-group",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [
        {
          path: "src/components/examples/checkbox-group.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/checkbox-group"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "checkbox-with-text": {
      name: "checkbox-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [
        {
          path: "src/components/examples/checkbox-with-text.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/checkbox-with-text"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "collapsible-demo": {
      name: "collapsible-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["collapsible"],
      files: [
        {
          path: "src/components/examples/collapsible-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/collapsible-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "dialog-demo": {
      name: "dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [
        {
          path: "src/components/examples/dialog-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/dialog-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "dialog-close-button": {
      name: "dialog-close-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog", "button"],
      files: [
        {
          path: "src/components/examples/dialog-close-button.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/dialog-close-button"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "menu-demo": {
      name: "menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["menu"],
      files: [
        {
          path: "src/components/examples/menu-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/menu-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "menu-checkboxes": {
      name: "menu-checkboxes",
      description: "",
      type: "registry:example",
      registryDependencies: ["menu", "checkbox"],
      files: [
        {
          path: "src/components/examples/menu-checkboxes.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/menu-checkboxes"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "menu-radio-group": {
      name: "menu-radio-group",
      description: "",
      type: "registry:example",
      registryDependencies: ["menu", "radio-group"],
      files: [
        {
          path: "src/components/examples/menu-radio-group.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/menu-radio-group"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "preview-card-demo": {
      name: "preview-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["preview-card"],
      files: [
        {
          path: "src/components/examples/preview-card-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/preview-card-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "input-demo": {
      name: "input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [
        {
          path: "src/components/examples/input-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/input-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "input-disabled": {
      name: "input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [
        {
          path: "src/components/examples/input-disabled.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/input-disabled"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "input-file": {
      name: "input-file",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [
        {
          path: "src/components/examples/input-file.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/input-file")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "input-with-button": {
      name: "input-with-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["input", "button"],
      files: [
        {
          path: "src/components/examples/input-with-button.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/input-with-button"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "input-with-label": {
      name: "input-with-label",
      description: "",
      type: "registry:example",
      registryDependencies: ["input", "button", "label"],
      files: [
        {
          path: "src/components/examples/input-with-label.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/input-with-label"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "input-with-text": {
      name: "input-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["input", "button", "label"],
      files: [
        {
          path: "src/components/examples/input-with-text.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/input-with-text"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "label-demo": {
      name: "label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["label"],
      files: [
        {
          path: "src/components/examples/label-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/label-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "popover-demo": {
      name: "popover-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["popover"],
      files: [
        {
          path: "src/components/examples/popover-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/popover-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "progress-demo": {
      name: "progress-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: [
        {
          path: "src/components/examples/progress-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/progress-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "radio-demo": {
      name: "radio-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["radio"],
      files: [
        {
          path: "src/components/examples/radio-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/radio-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "scroll-area-demo": {
      name: "scroll-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-area"],
      files: [
        {
          path: "src/components/examples/scroll-area-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/scroll-area-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "scroll-area-horizontal-demo": {
      name: "scroll-area-horizontal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-area"],
      files: [
        {
          path: "src/components/examples/scroll-area-horizontal-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/scroll-area-horizontal-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "select-demo": {
      name: "select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [
        {
          path: "src/components/examples/select-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/select-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "select-scrollable": {
      name: "select-scrollable",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [
        {
          path: "src/components/examples/select-scrollable.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/select-scrollable"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "separator-demo": {
      name: "separator-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["separator"],
      files: [
        {
          path: "src/components/examples/separator-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/separator-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "slider-demo": {
      name: "slider-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["slider"],
      files: [
        {
          path: "src/components/examples/slider-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/slider-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "switch-demo": {
      name: "switch-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["switch"],
      files: [
        {
          path: "src/components/examples/switch-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/switch-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "tabs-demo": {
      name: "tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [
        {
          path: "src/components/examples/tabs-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/tabs-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "tabs-custom-1": {
      name: "tabs-custom-1",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [
        {
          path: "src/components/examples/tabs-custom-1.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/tabs-custom-1"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "tabs-custom-2": {
      name: "tabs-custom-2",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [
        {
          path: "src/components/examples/tabs-custom-2.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/tabs-custom-2"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    // "textarea-demo": {
    //   name: "textarea-demo",
    //   description: "",
    //   type: "registry:example",
    //   registryDependencies: ["textarea"],
    //   files: [
    //     {
    //       path: "src/components/examples/textarea-demo.tsx",
    //       type: "registry:example",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(
    //     () => import("@/registry/default/example/textarea-demo.tsx"),
    //   ),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    // "textarea-disabled": {
    //   name: "textarea-disabled",
    //   description: "",
    //   type: "registry:example",
    //   registryDependencies: ["textarea"],
    //   files: [
    //     {
    //       path: "src/components/examples/textarea-disabled.tsx",
    //       type: "registry:example",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(
    //     () => import("@/registry/default/example/textarea-disabled.tsx"),
    //   ),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    // "textarea-form": {
    //   name: "textarea-form",
    //   description: "",
    //   type: "registry:example",
    //   registryDependencies: ["textarea", "form"],
    //   files: [
    //     {
    //       path: "src/components/examples/textarea-form.tsx",
    //       type: "registry:example",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(
    //     () => import("@/registry/default/example/textarea-form.tsx"),
    //   ),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    // "textarea-with-button": {
    //   name: "textarea-with-button",
    //   description: "",
    //   type: "registry:example",
    //   registryDependencies: ["textarea", "button"],
    //   files: [
    //     {
    //       path: "src/components/examples/textarea-with-button.tsx",
    //       type: "registry:example",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(
    //     () => import("@/registry/default/example/textarea-with-button.tsx"),
    //   ),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    // "textarea-with-label": {
    //   name: "textarea-with-label",
    //   description: "",
    //   type: "registry:example",
    //   registryDependencies: ["textarea", "label"],
    //   files: [
    //     {
    //       path: "src/components/examples/textarea-with-label.tsx",
    //       type: "registry:example",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(
    //     () => import("@/registry/default/example/textarea-with-label.tsx"),
    //   ),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    // "textarea-with-text": {
    //   name: "textarea-with-text",
    //   description: "",
    //   type: "registry:example",
    //   registryDependencies: ["textarea", "label"],
    //   files: [
    //     {
    //       path: "src/components/examples/textarea-with-text.tsx",
    //       type: "registry:example",
    //       target: "",
    //     },
    //   ],
    //   component: React.lazy(
    //     () => import("@/registry/default/example/textarea-with-text.tsx"),
    //   ),
    //   source: "",
    //   category: "",
    //   subcategory: "",
    //   chunks: [],
    // },
    "toggle-group-demo": {
      name: "toggle-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [
        {
          path: "src/components/examples/toggle-group-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/toggle-group-demo"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "toggle-demo": {
      name: "toggle-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "src/components/examples/toggle-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/toggle-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "toggle-disabled": {
      name: "toggle-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "src/components/examples/toggle-disabled.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/toggle-disabled"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "toggle-lg": {
      name: "toggle-lg",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "src/components/examples/toggle-lg.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/toggle-lg")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "toggle-outline": {
      name: "toggle-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "src/components/examples/toggle-outline.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/toggle-outline"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "toggle-sm": {
      name: "toggle-sm",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "src/components/examples/toggle-sm.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/toggle-sm")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "toggle-with-text": {
      name: "toggle-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "src/components/examples/toggle-with-text.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/components/examples/toggle-with-text"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "tooltip-demo": {
      name: "tooltip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: [
        {
          path: "src/components/examples/tooltip-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/components/examples/tooltip-demo")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
  },
}
